# This file was retrieved from https://postgrest.org/en/stable/explanations/install.html#containerized-postgrest-and-db-with-docker-compose
# Runs a docker compose file for a postgres database and a postgrest server
services:
  # Postgrest server
  server:
    container_name: postgrest-container
    image: postgrest/postgrest
    ports:
      - "3001:3000"
    env_file: 
      - ./.env
    environment:
      PGRST_DB_SCHEMA: public
    depends_on:
      - db

  # Postgres database
  db:
    container_name: db-container
    image: postgres
    ports:
      - "5432:5432"
    env_file: 
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

# Add this volumes section at the root level
volumes:
  postgres_data:
