version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgrest:
    image: postgrest/postgrest:v12.0.2
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@postgres:5432/app
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: postgres
    ports:
      - "3001:3000"

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    volumes:
      - ./apps/server:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/app
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev

# This is not configured correctly.
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:4000
    depends_on:
      - server
    command: npm run dev

volumes:
  postgres_data: 