services:
  postgrest:
    container_name: fullstack-assessment-postgrest
    image: postgrest/postgrest
    ports:
      - "3001:3000"
    env_file: 
      - ./.env
    environment:
      PGRST_DB_SCHEMA: public
    depends_on:
      - db
    networks:
      - app-network


  db:
    container_name: fullstack-assessment-postgres
    image: postgres
    ports:
      - "5432:5432"
    env_file: 
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  server:
    container_name: fullstack-assessment-server
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "8080:8080"
    env_file: 
      - ./.env
    depends_on:
      - db
      - postgrest
    networks:
      - app-network

  frontend:
    container_name: fullstack-assessment-frontend
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  postgres_data: 